receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
exporters:
  logging:
    verbosity: detailed
  logging/2:
    verbosity: detailed
processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500
  batch:

extensions:
  zpages/my-config:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ logging/2 ]
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ logging/2 ]
  extensions: [zpages/my-config]

  telemetry:
    logs:
      level: "debug"