receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  logging:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
  telemetry:
    logs:
      level: "debug"